name: Pterodactyl-Ubuntu

on: push

jobs:
  push:
    name: "yayebublya:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            erxson/yayebublya:latest
